# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Balancing Games
tagline:          'Or atleast trying to'
description:      'Why balance is important, how games are balanced and why game balancing is such a fun problem.'

url:              https://WJLKavanagh.github.io
baseurl:          /balancing_blog/

author:
  name:           'William Kavanagh'
  url:            https://twitter.com/BKavanagh1

paginate:         5
disqusShortname: spf13

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
