# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Balancing Games
tagline:          'Or atleast trying to'
description: >
'I'm William Kavanagh, a Computer Science Ph.D. student at the
University of Glasgow in the Formal Methods, Theory and Algorithms group. For my
research I am looking at making games fun using novel techniques. Outside of work
I am player of games. Currently I'm playing etc'
url:              https://WJLKavanagh.github.io
baseurl:          /balancing_blog/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
